### ISSUE TITLE
Issue on running this reppo

### ISSUE THREAD

**Issue by anandbhaskaran** [ednilsonamaral/simple-todo-list-vuejs#1]
Helloam newbie to the VueJS and I started to explore more on VueJs from this repo.  I am getting the following issue when I try to execute it.

![image](https://user-images.githubusercontent.com/6847984/36216965-8604a948-11b0-11e8-98c4-86e5113988ed.png)

**Comment by anandbhaskaran** [comment]
I renamed babel to babel-loader in webpack.config.js file.

As a next step I get the following error:
![image](https://user-images.githubusercontent.com/6847984/36217134-f265c6ee-11b0-11e8-8f04-9e0def8672d4.png)

**Comment by ednilsonamaral** [comment]
Hello, @anandbaskaran. This repo uses the RC version of lib. 

I created this repo just for studies. I did not work on him after that. To remedy these errors you would need to update the libs and code versions.
